---
sudo: required
language: node_js
node_js:
  - "6"
  - "7"
  - "8"
python:
  - "3.6"
services:
  - docker
cache:
  directories:
    - "node_modules"
addons:
  apt:
    packages:
      # needed to build o2r-meta
      - gcc
      - g++
      - python3-dev
      - libxml2-dev
      - libxslt-dev
      - gdal
      - gdal-dev
      - py-gdal
before_install:
  - docker --version
  - docker pull o2rproject/o2r-loader:latest
  - docker pull mongo:3.4
  - pip install --upgrade pip
  - pip install bagit
  - git clone --depth 1 -b master https://github.com/o2r-project/o2r-meta.git $HOME/meta
  - pip install -r requirements.txt
  - export MUNCHER_META_TOOL_EXE="python3 $HOME/meta/o2rmeta.py"
  - export MUNCHER_META_EXTRACT_MAPPINGS_DIR="$HOME/meta/broker/mappings"
install:
  - npm install
  - npm install -g mocha
before_script:
  - docker run --name mongodb -d -p 27017:27017 mongo:3.4
  - docker run --name testloader -d -p 8088:8088 --link mongodb:mongodb -v $HOME:/tmp/o2r -e LOADER_MONGODB=mongodb://mongodb:27017 -e DEBUG=* o2rproject/o2r-loader:latest
  - sleep 10
script:
  - DEBUG=muncher,executor,compendium,executor:*,muncher:* MUNCHER_BASEPATH=$HOME/ npm start &
  - DEBUG=* npm test
after_failure:
  - sleep 5
  - docker logs testloader
